export const VACANCY = [
  {
    title: 'Assistanse database administrator',
    number: '01',
    intro:
      'At Workers Benefit Fund we are always looking for experienced and innovative team members that are excited about leveling the playing field for everyone in the new gig economy workforce. Our goal is to give access & provide benefits to these new 100 million strong non-traditional workers who don’t have access to corporate benefit plans or traditional benefits. We are passionate about building tools & services to re-envision what is possible for gig workers.',
    position: 'Office Supervisor',
    location: 'Quito, Ecuador',
    jobBrief:
      'We are looking for a dynamic & innovative Office Supervisor to perform a variety of managerial and administrative tasks and support our company’s operations in Quito, Ecuador. This job will include, sourcing and recruiting local talent, handling HR matters, managing company calendars, handling travel arrangements, preparing expense reports, ensuring everyone in the team has what they require to perform their jobs, etc. To be successful in this role, you will need to be well-organized, have great time management skills and be able to act without guidance. Ultimately, you will contribute to the efficiency of our business by providing personalized and timely support to our team.',
    responsibilities1: [
      'Ensure the office is well maintained, running and that team members have what they need in order to perform their jobs.',
      'Provide "dotted-line" management support for all non-technical workers in the Quito office along with HR support to to the technical team.',
      'Manage vendor relationships and act as the main point of contact for all correspondence.',
      'Handle all contractor onboarding and off-boarding processes.',
      'Coordinate with the US-based operations team to maintain proper record keeping and internal request processes.',
      'Work with the Operations Manager on running projects to improve efficiency and ongoing processes.',
      'Organize company events, lunches, anniversary celebrations, anything required by management.',
      "Keep track of vendor's work hours.",
      'Act as the point of contact among executives, employees, clients and other external partners.',
    ],
    responsibilities2: [
      'Manage information flow in a timely and accurate manner.',
      'Make travel and accommodation arrangements.',
      'Act as an office manager.',
      'Tracking office supply inventory.',
      'Ordering needed office supplies.',
      'Scheduling office repairs and maintenance.',
      'Develop, implement and maintain budgetary and resource allocation plans.',
      'This includes preparing weekly, monthly or quarterly reports.',
      'Resolve internal staff conflicts effectively and to the benefit of all team members involved.',
      'Provide guidance and feedback to help others strengthen specific knowledge/skill areas.',
      'Ensure vendors and contractors adhere to company standards and Terms of Work.',
    ],
    requirements1: [
      'Two plus years of experience in a relevant role.',
      'Experienced with sourcing, recruiting and handling Human Resources matters (big plus).',
      'Comfortable with Google Calendar, GMail, Google Slides and MS Office Suite.',
      'Outstanding organizational and time management skills.',
    ],
    requirements2: [
      'Basic understanding of bookkeeping and accounting principals.',
      'Excellent English & Spanish verbal and written communications skills.',
      'Discretion and confidentiality.',
      'Bachelor’s degree (or equivalent) in business management or related field.',
    ],
  },
  {
    title: 'Assistanse database administrator',
    number: '02',
    intro:
      'At Workers Benefit Fund we are always looking for experienced and innovative team members that are excited about leveling the playing field for everyone in the new gig economy workforce. Our goal is to give access & provide benefits to these new 100 million strong non-traditional workers who don’t have access to corporate benefit plans or traditional benefits. We are passionate about building tools & services to re-envision what is possible for gig workers.',
    position: 'Office Supervisor',
    location: 'Quito, Ecuador',
    jobBrief:
      'We are looking for a dynamic & innovative Office Supervisor to perform a variety of managerial and administrative tasks and support our company’s operations in Quito, Ecuador. This job will include, sourcing and recruiting local talent, handling HR matters, managing company calendars, handling travel arrangements, preparing expense reports, ensuring everyone in the team has what they require to perform their jobs, etc. To be successful in this role, you will need to be well-organized, have great time management skills and be able to act without guidance. Ultimately, you will contribute to the efficiency of our business by providing personalized and timely support to our team.',
    responsibilities1: [
      'Ensure the office is well maintained, running and that team members have what they need in order to perform their jobs.',
      'Provide "dotted-line" management support for all non-technical workers in the Quito office along with HR support to to the technical team.',
      'Manage vendor relationships and act as the main point of contact for all correspondence.',
      'Handle all contractor onboarding and off-boarding processes.',
      'Coordinate with the US-based operations team to maintain proper record keeping and internal request processes.',
      'Work with the Operations Manager on running projects to improve efficiency and ongoing processes.',
      'Organize company events, lunches, anniversary celebrations, anything required by management.',
      "Keep track of vendor's work hours.",
      'Act as the point of contact among executives, employees, clients and other external partners.',
    ],
    responsibilities2: [
      'Manage information flow in a timely and accurate manner.',
      'Make travel and accommodation arrangements.',
      'Act as an office manager.',
      'Tracking office supply inventory.',
      'Ordering needed office supplies.',
      'Scheduling office repairs and maintenance.',
      'Develop, implement and maintain budgetary and resource allocation plans.',
      'This includes preparing weekly, monthly or quarterly reports.',
      'Resolve internal staff conflicts effectively and to the benefit of all team members involved.',
      'Provide guidance and feedback to help others strengthen specific knowledge/skill areas.',
      'Ensure vendors and contractors adhere to company standards and Terms of Work.',
    ],
    requirements1: [
      'Two plus years of experience in a relevant role.',
      'Experienced with sourcing, recruiting and handling Human Resources matters (big plus).',
      'Comfortable with Google Calendar, GMail, Google Slides and MS Office Suite.',
      'Outstanding organizational and time management skills.',
    ],
    requirements2: [
      'Basic understanding of bookkeeping and accounting principals.',
      'Excellent English & Spanish verbal and written communications skills.',
      'Discretion and confidentiality.',
      'Bachelor’s degree (or equivalent) in business management or related field.',
    ],
  },
  {
    title: 'Assistanse database administrator',
    number: '03',
    intro:
      'At Workers Benefit Fund we are always looking for experienced and innovative team members that are excited about leveling the playing field for everyone in the new gig economy workforce. Our goal is to give access & provide benefits to these new 100 million strong non-traditional workers who don’t have access to corporate benefit plans or traditional benefits. We are passionate about building tools & services to re-envision what is possible for gig workers.',
    position: 'Office Supervisor',
    location: 'Quito, Ecuador',
    jobBrief:
      'We are looking for a dynamic & innovative Office Supervisor to perform a variety of managerial and administrative tasks and support our company’s operations in Quito, Ecuador. This job will include, sourcing and recruiting local talent, handling HR matters, managing company calendars, handling travel arrangements, preparing expense reports, ensuring everyone in the team has what they require to perform their jobs, etc. To be successful in this role, you will need to be well-organized, have great time management skills and be able to act without guidance. Ultimately, you will contribute to the efficiency of our business by providing personalized and timely support to our team.',
    responsibilities1: [
      'Ensure the office is well maintained, running and that team members have what they need in order to perform their jobs.',
      'Provide "dotted-line" management support for all non-technical workers in the Quito office along with HR support to to the technical team.',
      'Manage vendor relationships and act as the main point of contact for all correspondence.',
      'Handle all contractor onboarding and off-boarding processes.',
      'Coordinate with the US-based operations team to maintain proper record keeping and internal request processes.',
      'Work with the Operations Manager on running projects to improve efficiency and ongoing processes.',
      'Organize company events, lunches, anniversary celebrations, anything required by management.',
      "Keep track of vendor's work hours.",
      'Act as the point of contact among executives, employees, clients and other external partners.',
    ],
    responsibilities2: [
      'Manage information flow in a timely and accurate manner.',
      'Make travel and accommodation arrangements.',
      'Act as an office manager.',
      'Tracking office supply inventory.',
      'Ordering needed office supplies.',
      'Scheduling office repairs and maintenance.',
      'Develop, implement and maintain budgetary and resource allocation plans.',
      'This includes preparing weekly, monthly or quarterly reports.',
      'Resolve internal staff conflicts effectively and to the benefit of all team members involved.',
      'Provide guidance and feedback to help others strengthen specific knowledge/skill areas.',
      'Ensure vendors and contractors adhere to company standards and Terms of Work.',
    ],
    requirements1: [
      'Two plus years of experience in a relevant role.',
      'Experienced with sourcing, recruiting and handling Human Resources matters (big plus).',
      'Comfortable with Google Calendar, GMail, Google Slides and MS Office Suite.',
      'Outstanding organizational and time management skills.',
    ],
    requirements2: [
      'Basic understanding of bookkeeping and accounting principals.',
      'Excellent English & Spanish verbal and written communications skills.',
      'Discretion and confidentiality.',
      'Bachelor’s degree (or equivalent) in business management or related field.',
    ],
  },
]
